jenkins_agent_home: /opt/jenkins
jenkins_agent_user: jenkins
jenkins_agent_group: jenkins
jenkins_agent_version: "4.10"
jenkins_master_url: "https://jenkins.manhhung20033004.io.vn:8080"
jenkins_agent_name: "agent-01"
jenkins_agent_secret: "300420"