#SPDX-License-Identifier: MIT-0
---
# handlers file for kind
- name: Restart Docker
  ansible.builtin.systemd:
    name: docker
    state: restarted
  become: yes
  become_user: root
  listen: Restart Docker

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes
  become: yes
  become_user: root
  listen: Reload systemd
  