- name: Check if kind is installed
  ansible.builtin.command: kind --version
  register: kind_check
  ignore_errors: yes

- name: Install kind if not installed
  ansible.builtin.shell: curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.20.0/kind-linux-amd64 && chmod +x ./kind && mv ./kind /usr/local/bin/kind
  when: kind_check.rc != 0
  become: yes
  become_user: root
  args:
    creates: /usr/local/bin/kind
  tags: install

- name: install kubectl
  ansible.builtin.shell: curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
  args:
    creates: /usr/local/bin/kubectl
  become: yes
  become_user: root
  tags: install