
- name: Symlink nginx.conf
  ansible.builtin.file:
    src: /opt/configs/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    state: link
    owner: root
    group: root

- name: Symlink page-not-found.html
  ansible.builtin.file:
    src: /opt/configs/nginx/page-not-found.html
    dest: /usr/share/nginx/html/page-not-found.html
    state: link
    owner: root
    group: root

- name: Symlink mime.types
  ansible.builtin.file:
    src: /opt/configs/nginx/mime.types
    dest: /etc/nginx/mime.types
    state: link
    owner: root
    group: root

- name: Symlink SSL cert fullchain.pem for nginx
  ansible.builtin.file:
    src: /opt/configs/nginx/fullchain.pem
    dest: /etc/ssl/certs/fullchain.pem
    state: link
    owner: root
    group: root

- name: Symlink SSL key key.pem for nginx
  ansible.builtin.file:
    src: /opt/configs/nginx/key.pem
    dest: /etc/ssl/private/key.pem
    state: link
    owner: root
    group: root
    mode: '0600'