- name: Remove old nginx.conf if exists
  ansible.builtin.file:
    path: /etc/nginx/nginx.conf
    state: absent
  ignore_errors: yes

- name: Symlink nginx.conf
  ansible.builtin.file:
    src: /opt/configs/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    state: link
    owner: root
    group: root

- name: Symlink proxy.conf
  ansible.builtin.file:
    src: /opt/configs/nginx/include/proxy.conf
    dest: /etc/nginx/conf.d/proxy.conf
    state: link
    owner: root
    group: root

- name: Symlink page-not-found.html
  ansible.builtin.file:
    src: /opt/configs/nginx/page-not-found.html
    dest: /usr/share/nginx/html/page-not-found.html
    state: link
    owner: root
    group: root
