- name: Start and enable nginx service
  ansible.builtin.systemd:
        name: nginx
        state: started
        enabled: yes

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Ensure nginx is listening on port 80
  ansible.builtin.ufw:
    rule: allow
    port: '80'
    proto: tcp
    state: enabled

- name: Create a simple index.html file
  ansible.builtin.copy:
    dest: /var/www/html/index.html
    content: "<h1>Welcome to Nginx Web Server!</h1>"
    owner: www-data
    group: www-data
    mode: '0644'