- name: Install prerequisites
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
      - ubuntu-keyring
    state: present

- name: Import an official nginx signing key so apt could verify the packages authenticity.
  ansible.builtin.apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present

- name: Add nginx repository
  command: curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor | sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

- name: set up the apt repository for stable nginx packages
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] http://nginx.org/packages/ubuntu `lsb_release -cs` nginx"
    state: present
    filename: nginx
    update_cache: yes

- name: Set up repository pinning to prefer our packages over distribution-provided ones
  command: echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" | sudo tee /etc/apt/preferences.d/99nginx    | sudo tee /etc/apt/preferences.d/99nginx

- name: install nginx web server
  apt:
    name: nginx
    state: present
    update_cache: yes
  