- name: Transfer config files to server
  import_tasks: transferFile.yml

- name: check port 8080
  ansible.builtin.command: sudo netstat -tuln | grep 8080
  register: port_8080_check
  ignore_errors: yes

- name: Install nginx web server
  import_tasks: installNginx.yml

- name: Configure nginx web server
  import_tasks: configNginx.yml

- name: Start and enable nginx service
  import_tasks: enableNginx.yml