- name: Sync nginx config files to server
  ansible.builtin.synchronize:
    src: roles/nginx/files/
    dest: /opt/configs/nginx/
    recursive: yes

- name: Sync ssh certificates files to server
  ansible.builtin.synchronize:
    src: files/sshkey/
    dest: /opt/configs/nginx/
    recursive: yes