# filepath: /ansible-project/ansible-project/roles/common/defaults/main.yml
---
# Default variables for the common role
########### Elasticsearch #########
elasticsearch_version: "0.0.1"
elasticsearch_home: "/opt/elasticsearch"
elasticsearch_http_port: 9200
