- src: "ansible-project/ansible-project/requirements.yml"
- name: geerlingguy.apache
  src: https://github.com/geerlingguy/ansible-role-apache.git
  version: 3.0.0
- name: geerlingguy.mysql
  src: https://github.com/geerlingguy/ansible-role-mysql.git
  version: 2.9.0
- name: geerlingguy.php
  src: https://github.com/geerlingguy/ansible-role-php.git
  version: 3.0.0
- name: geerlingguy.php-redis
  src: https://github.com/geerlingguy/ansible-role-php-redis.git
  version: 2.0.0