- name: Create jenkins group
  ansible.builtin.group:
    name: "{{ agent_group }}"
    state: present

- name: create jenkins user
  ansible.builtin.user:
    name: "{{ agent_user }}"
    group: "{{ agent_group }}"

- name: Create directory for Jenkins agent
  ansible.builtin.file:
    path: "{{ agent_home }}"
    state: directory
    owner: "{{ agent_user }}"
    group: "{{ agent_group }}"
    mode: '0755'

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install fontconfig package
  apt:
    name: fontconfig
    state: present
    update_cache: yes

- name: install Java (openjdk-21-jre)
  apt:
    name: openjdk-21-jre
    state: present

- name: Create .ssh for SSH mode (so controller can connect)
  ansible.builtin.file:
    path: "/home/{{ agent_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ agent_user }}"
    group: "{{ agent_user }}"
  when: agent_mode == 'ssh'

- name: Authorize controller public key (SSH mode)
  ansible.builtin.lineinfile:
    path: "/home/{{ agent_user }}/.ssh/authorized_keys"
    create: yes
    line: "{{ controller_pubkey }}"
    owner: "{{ agent_user }}"
    group: "{{ agent_user }}"
    mode: "0600"
  when: agent_mode == 'ssh'

- name: Download Jenkins agent jar
  ansible.builtin.get_url:
    url: "{{ jenkins_url }}/jnlpJars/agent.jar"
    dest: "{{ agent_home }}/agent.jar"
    mode: '0755'
    owner: "{{ agent_user }}"
    group: "{{ agent_group }}"

- name: Ensure Jenkins agent service file is present
  ansible.builtin.template:
    src: jenkins-agent.service.j2
    dest: /etc/systemd/system/jenkins-agent.service
    mode: '0644'
    owner: root
    group: root
  notify: Reload systemd

- name: Start and enable Jenkins agent service
  ansible.builtin.systemd:
        name: jenkins-agent
        state: started
        enabled: yes
  when: agent_mode == 'ssh'  # Only start service in SSH mode; JNLP mode requires manual start
  notify: Reload systemd

