- name: Install prerequisites
  apt:
    name: 
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  become: true

- name: Add Docker GPG key
  shell: |
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: true

- name: Install Docker and Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
  become: true

- name: Ensure Docker service is started
  service:
    name: docker
    state: started
    enabled: true
  become: true

- name: Copy Dockerfile for Jenkins Agent
  copy:
    src: Dockerfile.agent
    dest: /home/{{ ansible_user }}/Dockerfile.agent
  become: true

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /home/{{ ansible_user }}/docker-compose.yml
  become: true

- name: Build Jenkins Agent Docker image
  shell: |
    docker build -t my-jenkins-agent -f /home/{{ ansible_user }}/Dockerfile.agent /home/{{ ansible_user }}
  become: true

- name: Start Jenkins Agent container using Docker Compose
  shell: |
    docker-compose -f /home/{{ ansible_user }}/docker-compose.yml up -d
  become: true