- name: create jenkins user
  ansible.builtin.user:
    name: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
- name: Create directory for Jenkins slave
  ansible.builtin.file:
    path: "{{ jenkins_slave_home }}"
    state: directory
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
    mode: '0755'
- name: Update apt cache
  apt:
      update_cache: yes
      cache_valid_time: 3600
- name: Install Java (OpenJDK 11)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes
- name: Download Jenkins slave jar
  ansible.builtin.get_url:
    url: "{{ jenkins_master_url }}/jnlpJars/slave.jar"
    dest: "{{ jenkins_slave_home }}/slave.jar"
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
    mode: '0755'
- name: Ensure Jenkins slave service file is present
  ansible.builtin.template:
    src: jenkins-slave.service.j2
    dest: /etc/systemd/system/jenkins-slave.service
    owner: root
    group: root
    mode: '0644'
- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes
- name: Enable and start Jenkins slave service
  ansible.builtin.systemd:
    name: jenkins-slave
    state: started
    enabled: yes
- name: Verify Jenkins slave service status
  ansible.builtin.systemd:
    name: jenkins-slave
    register: jenkins_slave_status

- name: Get Jenkins initial admin password
  command: cat /var/lib/jenkins/secrets/initialAdminPassword
  register: jenkins_password
  changed_when: false

- name: Display Jenkins initial password
  debug:
        msg: "Jenkins initial admin password: {{ jenkins_password.stdout }}"