- name: Create jenkins group
  ansible.builtin.group:
    name: "{{ jenkins_slave_group }}"
    state: present

- name: create jenkins user
  ansible.builtin.user:
    name: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"

- name: Create directory for Jenkins slave
  ansible.builtin.file:
    path: "{{ jenkins_slave_home }}"
    state: directory
    owner: "{{ jenkins_slave_user }}"
    group: "{{ jenkins_slave_group }}"
    mode: '0755'

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Java (OpenJDK 11)
  apt:
    name: openjdk-11-jdk
    state: present
    update_cache: yes

- name: Add Jenkins GPG key
  apt_key:
        url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
        state: present

- name: Add Jenkins repository
  apt_repository:
        repo: "deb https://pkg.jenkins.io/debian-stable binary/"
        state: present
        update_cache: yes

- name: Install Jenkins
  apt:
    name: jenkins
    state: present
    update_cache: yes

- name: Start and enable Jenkins service
  systemd:
        name: jenkins
        state: started
        enabled: yes

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Jenkins slave service
  ansible.builtin.systemd:
    name: jenkins-slave
    state: started
    enabled: yes

- name: Verify Jenkins slave service status
  ansible.builtin.systemd:
    name: jenkins-slave
    register: jenkins_slave_status