- name: Start and enable Jenkins service
  ansible.builtin.systemd:
        name: jenkins
        state: started
        enabled: yes

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Enable and start Jenkins slave service
  ansible.builtin.systemd:
    name: jenkins-slave
    state: started
    enabled: yes

- name: Verify Jenkins slave service status
  ansible.builtin.systemd:
    name: jenkins-slave
    register: jenkins_slave_status