- name: Start and enable Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: started
    enabled: yes

- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes