- name: Reload systemd to recognize the new service
  ansible.builtin.systemd:
    daemon_reload: yes
  
- name: Restart Jenkins service
  ansible.builtin.systemd:
    name: jenkins
    state: restarted
    enabled: yes