---
- name: Install Jenkins
  apt:
    name: jenkins
    state: present
  become: true

- name: Ensure Jenkins is started and enabled
  service:
    name: jenkins
    state: started
    enabled: true
  become: true
