- name: Add OpenJDK PPA
  apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
  become: true

- name: Update apt cache (after adding PPA)
  apt:
    update_cache: yes
  become: true

- name: Install Java (required for Jenkins)
  apt:
    name: openjdk-17-jdk
    state: present
  become: true
