---
- include_tasks: install_java.yml
  tags:
    - install_java

- include_tasks: setup_jenkins_repo.yml
  tags:
    - setup_repo

- include_tasks: install_jenkins.yml
  tags:
    - install_jenkins

- include_tasks: restore_backup.yml
  tags:
    - restore_backup
