- name: Add Jenkins repository key (using gpg and tee)
  shell: |
    curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | gpg --dearmor | sudo tee /usr/share/keyrings/jenkins-archive-keyring.gpg > /dev/null
  become: true

- name: Add Jenkins repository (signed-by)
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/jenkins-archive-keyring.gpg] http://pkg.jenkins.io/debian-stable binary/"
    state: present
  become: true

- name: Update apt cache (after adding Jenkins repo)
  apt:
    update_cache: yes
  become: true
