FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -qy --no-install-recommends \
        openjdk-17-jdk \
        git \
        maven \
        openssh-server && \
    mkdir -p /var/run/sshd && \
    apt-get -qy autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN useradd -m jenkins -s /bin/bash && \
    mkdir -p /home/jenkins/.ssh/

COPY jenkins_agent_key.pub /home/jenkins/.ssh/authorized_keys

RUN chown -R jenkins:jenkins /home/jenkins/.ssh/ && \
    chmod 700 /home/jenkins/.ssh && \
    chmod 600 /home/jenkins/.ssh/authorized_keys

EXPOSE 22

CMD ["/usr/sbin/sshd", "-D"]
