version: '3'

services:
  # jenkins:
  #   image: jenkins/jenkins:lts
  #   privileged: true
  #   user: root
  #   ports:
  #     - "7080:8080"
  #     - "50000:50000"
  #   container_name: jenkins
  #   volumes:
  #     - ~/jenkins-data:/var/jenkins_home
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   networks:
  #     - jenkins

  agent:
    build:
      context: ./
      dockerfile: Dockerfile.agent
    image: my-jenkins-agent
    container_name: agent
    user: root
    ports:
      - "2222:22"
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDGhdIuv4cg6PSZGCBdK8mkbBhW0xl/n0jK8XsSF+trHypbKWFeOn9ktmnhAxSZpPRYY7GHORiQ458Teer3FbvV/SPZPRHe204XxlqhMoFJBohTgK/evqRWV5Z510TTHF1j7avipOxuuWPrb0h66LRJs662S7IzSUB/hsDSmsHdWZDod4dWkdjlnzya0/RcWyH12/iHYafnBCb+2kIvp3be5U0voKKSOQVdr8tviri7xOkC8rRHhlizgU1pyNEPeU2oK9aZ5hvOWWeXCIK24FafUIjvBKlR3vu6zZGK8z2sIB7kDeFygS/6tOt0RAfJxnxvAoxJlYSV0hoPiFfNSHpiLqcMsUianqsJqhcXld8vU1zOJFZlbyeqNorxtiCO3+Uy7cviG0jcTNYqRbE20zXYHSmHA89SsEiTjLso1M1Q1fQPsSuV0+y8kVYK1eGFBRA5AlfV0MKsIUccZJWZ8d7INMw53UEiWij9NxRPAZGQR3qk56MfvkHUY5+chbwFonZalrpUbkisj/JoTVX6/o1Z/NkNW0DNojivNfJshWezC2ICBGB3wOUr5V+HfQAjvptG61dIzl7oAWZQhbygcLlNNmL+cVBA75dLCBfCASntDO51RJXv4WfhgGEnh0TpT+h/Z0j0MlLfWAqBWa21RH6Su/UzwNbLZIpavTgBwKZ5GQ== hungnm@vm1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
      - /usr/bin/docker:/usr/bin/docker
    # networks:
    #   - jenkins

# networks:
#   jenkins:
#     external: true