- name: Ensure common packages are installed
  apt:
    name:
      - git
      - curl
      - vim
    state: present

- name: Create a directory for application
  file:
    path: /opt/myapp
    state: directory

- name: Copy application files
  copy:
    src: files/
    dest: /opt/myapp/
    owner: root
    group: root
    mode: '0755'

- name: Start application service
  systemd:
    name: myapp
    state: started
    enabled: yes