- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Ensure nfs-kernel-server is installed
  ansible.builtin.apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes
    cache_valid_time: 3600